### ISSUE TITLE
Docker Image Build did not complete...

### ISSUE THREAD

**Issue by curtcorum** [BrainImAccs/fatbACPC#4]
On building the Docker image, it made it a long way but failed at the following step:

=> ERROR [6/6] RUN set -eux   && git clone https://github.com/BrainImAccs/BrainSTEM.git /opt/BrainSTEM   && cd /opt/BrainSTEM   && git checkout main   && git config submodule.modules/fatbACPC.url ht  0.9s

[6/6] RUN set -eux   && git clone https://github.com/BrainImAccs/BrainSTEM.git /opt/BrainSTEM   && cd /opt/BrainSTEM   && git checkout main   && git config submodule.modules/fatbACPC.url https://github.com/BrainImAccs/fatbACPC.git   && git submodule update --init modules/fatbACPC   && cd /opt/BrainSTEM/modules/fatbACPC   && git checkout main   && cp       /opt/BrainSTEM/modules/fatbACPC/setup.fatbACPC.bash-template       /opt/BrainSTEM/modules/fatbACPC/setup.fatbACPC.bash   && cat /opt/BrainSTEM/setup.brainstem.bash-template |       sed         -e "s%^FSLDIR=/path/to/fsl-.*%FSLDIR=/opt/fsl-6.0.4%"       > /opt/BrainSTEM/setup.brainstem.bash   && cp       /opt/BrainSTEM/tools/startJob.bash-template       /opt/BrainSTEM/tools/startJob.bash   && useradd --system --user-group --create-home --uid 999 bia   && echo '#!/usr/bin/env bash' >> /opt/entry.bash   && echo 'bash /opt/BrainSTEM/incoming/incoming.bash &' >> /opt/entry.bash   && echo 'bash /opt/BrainSTEM/received/queue.bash &' >> /opt/entry.bash   && echo 'wait' >> /opt/entry.bash   && chmod 755 /opt/entry.bash /opt/BrainSTEM/tools/startJob.bash   && chown bia:bia /opt/BrainSTEM/incoming /opt/BrainSTEM/received:
#0 0.347 + git clone https://github.com/BrainImAccs/BrainSTEM.git /opt/BrainSTEM
#0 0.351 Cloning into '/opt/BrainSTEM'...
#0 0.794 + cd /opt/BrainSTEM
#0 0.794 + git checkout main
#0 0.802 Already on 'main'
#0 0.803 Your branch is up to date with 'origin/main'.
#0 0.803 + git config submodule.modules/fatbACPC.url https://github.com/BrainImAccs/fatbACPC.git
#0 0.808 + git submodule update --init modules/fatbACPC
#0 0.879 error: pathspec 'modules/fatbACPC' did not match any file(s) known to git

**Comment by crubb** [comment]
Dear curtcorum,

Thanks for the reminder. The build for fatbACPC is currently broken because I changed the dependencies while working on [veganbagel](https://github.com/BrainImAccs/veganbagel), to add brain age gap estimation. Before, veganbagel was a module to BrainSTEM. Now, BrainSTEM depends on veganbagel, which allows for a cleaner setup.

I'm working on fixing fatbACPC and should have it done in 2-3 days.

Apologies for the inconvenience!

Best,
crubb

**Comment by curtcorum** [comment]
@crubb 

Thanks! Looking forward to using fatbACPC!

**Comment by crubb** [comment]
Should be fixed, can you take it for a spin? Thank you!

**Comment by curtcorum** [comment]
@crubb
Thanks, build worked great after making sure the BrainSTEM submodule was updated!
Now going to try things out!

~/src/fatbACPC$ git submodule update --init BrainSTEM
Submodule 'BrainSTEM' (https://github.com/BrainImAccs/BrainSTEM.git) registered for path 'BrainSTEM'
Cloning into '/home/curt/src/fatbACPC/BrainSTEM'...
Submodule path 'BrainSTEM': checked out 'dcf58463431c27bbd95e779b12219bc45f80f3d7'


~/src/fatbACPC$ docker build -t fatbacpc ./
[+] Building 51.8s (20/20) FINISHED                                                                                                                                                                 
 => [internal] load .dockerignore                                                                                                                                                              0.0s
 => => transferring context: 50B                                                                                                                                                               0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                           0.0s
 => => transferring dockerfile: 4.92kB                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/library/neurodebian:bullseye-non-free                                                                                                               0.5s
 => [internal] load metadata for docker.io/mambaorg/micromamba:1.5.3                                                                                                                           0.5s
 => [internal] load build context                                                                                                                                                              0.0s
 => => transferring context: 166.18kB                                                                                                                                                          0.0s
 => [micromamba 1/1] FROM docker.io/mambaorg/micromamba:1.5.3@sha256:d20c621f3ae42f50f380166b15b6c88b14fa62ab6ea188f2cef33451d64057c7                                                          0.0s
 => [dcm2niix-builder 1/2] FROM docker.io/library/neurodebian:bullseye-non-free@sha256:1908acf9c8692e43d73ed134d34748be5e6ed6eb18d1eceaaa9aca2c9507833c                                        0.0s
 => CACHED [stage-2  2/12] RUN set -eux   && apt-get update -qq   && apt-get -y upgrade   && apt-get install -y -q --no-install-recommends       apt-utils       bzip2       ca-certificates   0.0s
 => CACHED [dcm2niix-builder 2/2] RUN set -eux   && echo Building dcm2niix v1.0.20210317   && apt-get update -qq   && apt-get install -y -q --no-install-recommends       ca-certificates      0.0s
 => CACHED [stage-2  3/12] COPY --from=dcm2niix-builder /opt/dcm2niix /opt/dcm2niix                                                                                                            0.0s
 => CACHED [stage-2  4/12] COPY --from=micromamba /bin/micromamba /bin/micromamba                                                                                                              0.0s
 => CACHED [stage-2  5/12] COPY --from=micromamba /usr/local/bin/_activate_current_env.sh /usr/local/bin/_activate_current_env.sh                                                              0.0s
 => CACHED [stage-2  6/12] COPY --from=micromamba /usr/local/bin/_dockerfile_shell.sh /usr/local/bin/_dockerfile_shell.sh                                                                      0.0s
 => CACHED [stage-2  7/12] COPY --from=micromamba /usr/local/bin/_entrypoint.sh /usr/local/bin/_entrypoint.sh                                                                                  0.0s
 => CACHED [stage-2  8/12] COPY --from=micromamba /usr/local/bin/_dockerfile_initialize_user_accounts.sh /usr/local/bin/_dockerfile_initialize_user_accounts.sh                                0.0s
 => CACHED [stage-2  9/12] COPY --from=micromamba /usr/local/bin/_dockerfile_setup_root_prefix.sh /usr/local/bin/_dockerfile_setup_root_prefix.sh                                              0.0s
 => [stage-2 10/12] COPY --chown=999:999 . /opt/bia                                                                                                                                            0.1s
 => [stage-2 11/12] RUN set -eux   && /usr/local/bin/_dockerfile_initialize_user_accounts.sh   && /usr/local/bin/_dockerfile_setup_root_prefix.sh   && micromamba install --yes --name base   37.7s
 => [stage-2 12/12] RUN set -eux   && cp       /opt/bia/setup.fatbACPC.bash-template       /opt/bia/setup.fatbACPC.bash   && cat /opt/bia/BrainSTEM/setup.brainstem.bash-template |       sed  0.4s 
 => exporting to image                                                                                                                                                                        13.0s 
 => => exporting layers                                                                                                                                                                       13.0s 
 => => writing image sha256:543dc63b3bd599f17b4a4fd4022855a20b4294622f5ca0a276ab67f91713e2e5                                                                                                   0.0s 
 => => naming to docker.io/library/fatbacpc

**Comment by curtcorum** [comment]
@crubb

Help appreciated!

I have started the container with:

```
$ docker run -it -p 10104:10104/tcp --env called_aetitle=ORTHANC --env peer=127.0.0.1 --env port=4242 -t fatbacpc

This script takes a directory with DICOM files of a CT or (3D) MR brain scan as input and then
aligns that scan with a reference volume, such as the MNI brain atlas.

 When no arguments are given, the container will start in daemon mode and listen
 for incoming DICOM connections.

 More help may be found when starting the container with the "--help" argument.

Dummy startup for the simple queue system performed.
Dummy startup for the simple queue system performed.
Dummy startup for the simple queue system performed.
Dummy startup for the simple queue system performed.
```

So all seems good, but I am not able to access the container port via Orthanc. Telnet says it is there but it drops immediately. Am I doing some sort of noob thing as I am not a Docker expert...

![orthanc_fatacpc](https://github.com/BrainImAccs/fatbACPC/assets/1796102/335c7b7c-c0c8-4d15-96f3-9b3b8d526f73)

```
$ telnet localhost 10104
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by curtcorum** [comment]
```
$ curl -X POST http://localhost:8042/modalities/fatacpc/echo -d '{}'
{
   "Details" : "DicomAssociation - connecting to AET \"fatacpc\": TCP Initialization Error: Connection refused",
   "HttpError" : "Internal Server Error",
   "HttpStatus" : 500,
   "Message" : "Error in the network protocol",
   "Method" : "POST",
   "OrthancError" : "Error in the network protocol",
   "OrthancStatus" : 9,
   "Uri" : "/modalities/fatacpc/echo"
}
```

**Comment by crubb** [comment]
There is actually a simple [storescp](https://support.dcmtk.org/docs/storescp.html) listening on port 10104 to which you can send DICOM files using the DICOM protocol, e.g. using [storescu](https://support.dcmtk.org/docs/storescu.html).

fatbACPC will then process the files and send the images back as DICOM over the network. So you want to expose e.g. storescp on your local machine, or you use something like [Horos](https://horosproject.org/), which can both send and receive DICOM files when configure properly.

**Edit:** DICOM files are sent back to the `called_aetitle` at the `peer` and `port` you configured using the environment variables. Make sure the Docker container can speer to that `peer:port`.
